# Generated by Django 2.2.2 on 2019-07-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=30)),
                ('setor', models.CharField(max_length=25)),
                ('inicio', models.DateField()),
                ('saida', models.DateField()),
                ('pc', models.CharField(max_length=5)),
                ('cargo', models.CharField(max_length=30)),
            ],
        ),
    ]
